-- MySQL Script generated by MySQL Workbench
-- qui 27 jun 2019 13:01:50 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Alumaq
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Alumaq
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Alumaq` DEFAULT CHARACTER SET utf8mb4 ;
USE `Alumaq` ;

-- -----------------------------------------------------
-- Table `Alumaq`.`cargos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alumaq`.`cargos` ;

CREATE TABLE IF NOT EXISTS `Alumaq`.`cargos` (
  `id` INT(11) NOT NULL,
  `funcao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Alumaq`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alumaq`.`endereco` ;

CREATE TABLE IF NOT EXISTS `Alumaq`.`endereco` (
  `id` INT(11) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` INT(11) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Alumaq`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alumaq`.`cliente` ;

CREATE TABLE IF NOT EXISTS `Alumaq`.`cliente` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `data_nascimento` DATETIME NOT NULL,
  `endereco_id` INT(11) NOT NULL,
  `telefone1` VARCHAR(45) NOT NULL,
  `telefone2` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cliente_1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `Alumaq`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Alumaq`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alumaq`.`funcionario` ;

CREATE TABLE IF NOT EXISTS `Alumaq`.`funcionario` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `data_nascimento` DATETIME NOT NULL,
  `salario` DOUBLE NOT NULL,
  `endereco_id` INT(11) NULL DEFAULT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `telefone1` VARCHAR(45) NOT NULL,
  `telefone2` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  CONSTRAINT `fk_funcionario_1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `Alumaq`.`endereco` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Alumaq`.`contrato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alumaq`.`contrato` ;

CREATE TABLE IF NOT EXISTS `Alumaq`.`contrato` (
  `id` INT(11) NOT NULL,
  `cliente_id` INT(11) NOT NULL,
  `funcionario_id` INT(11) NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NULL DEFAULT NULL,
  `valorp1` DOUBLE NOT NULL,
  `valorp2` DOUBLE NULL DEFAULT NULL,
  `tipo` ENUM('LOCACAO', 'VENDA') NOT NULL,
  `multa` VARCHAR(45) NULL DEFAULT NULL,
  `fase` ENUM('FASE1', 'FASE2', 'FINALIZADO') NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_contrato_1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `Alumaq`.`cliente` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_2`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `Alumaq`.`funcionario` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Alumaq`.`equipamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alumaq`.`equipamento` ;

CREATE TABLE IF NOT EXISTS `Alumaq`.`equipamento` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `setor` ENUM('LOCACAO', 'VENDA') NOT NULL,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  `disponivel` ENUM('TRUE', 'FALSE') NOT NULL,
  `valor` DOUBLE NOT NULL,
  `qtd_estoque` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Alumaq`.`contrato_equipamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alumaq`.`contrato_equipamento` ;

CREATE TABLE IF NOT EXISTS `Alumaq`.`contrato_equipamento` (
  `id_contrato` INT(11) NOT NULL,
  `id_equipamento` INT(11) NOT NULL,
  `qtd` INT(11) NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`id_contrato`, `id_equipamento`),
  CONSTRAINT `fk_contrato_equipamento_1`
    FOREIGN KEY (`id_contrato`)
    REFERENCES `Alumaq`.`contrato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_equipamento_2`
    FOREIGN KEY (`id_equipamento`)
    REFERENCES `Alumaq`.`equipamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Alumaq`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Alumaq`.`usuario` ;

CREATE TABLE IF NOT EXISTS `Alumaq`.`usuario` (
  `id` INT(11) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `funcionario_id` INT(11) NOT NULL,
  `cargo` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  CONSTRAINT `fk_usuario_1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `Alumaq`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_2`
    FOREIGN KEY (`cargo`)
    REFERENCES `Alumaq`.`cargos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
